"""empty message

Revision ID: 357aa184cf04
Revises: 83d74c6f5de2
Create Date: 2025-03-12 11:15:35.402020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '357aa184cf04'
down_revision: Union[str, None] = '83d74c6f5de2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vouchers', sa.Column('reference', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'vouchers', ['reference'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vouchers', type_='unique')
    op.drop_column('vouchers', 'reference')
    # ### end Alembic commands ###
