"""empty message

Revision ID: 36ba13af6589
Revises: 8084bd8af4f6
Create Date: 2025-03-11 10:17:15.594806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36ba13af6589'
down_revision: Union[str, None] = '8084bd8af4f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vouchers', sa.Column('validity_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vouchers', 'validity_days')
    # ### end Alembic commands ###
