"""empty message

Revision ID: 6841d2ba7bb6
Revises: 1d98cbe68afc
Create Date: 2025-03-12 16:04:26.300488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6841d2ba7bb6'
down_revision: Union[str, None] = '1d98cbe68afc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
