"""Your migration message1

Revision ID: 904ff7b699de
Revises: b80364f35989
Create Date: 2025-03-04 08:13:54.833469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '904ff7b699de'
down_revision: Union[str, None] = 'b80364f35989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add the column with a default value
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))

    # Step 2: Update existing rows with a default username (modify as needed)
    op.execute("UPDATE users SET username = 'default_username' WHERE username IS NULL")

    # Step 3: Alter column to NOT NULL
    op.alter_column('users', 'username', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
